## Requirements

- name: Nginx root web folders creation
  file:
    path: "/home/web/giarrizzo.fr/home/"
    owner: bruno
    group: www-data
    state: directory
    mode: 0755

- name: Nginx log folders creation
  file:
    path: "/var/log/nginx/giarrizzo.fr/"
    owner: www-data
    group: adm
    state: directory
    mode: 0755

## vHost Config

- name: Site Install = Giarrizzo.fr
  template:
    src: giarrizzo.fr.conf
    dest: /etc/nginx/sites-enabled/001-giarrizzo.fr.conf
  notify: restart nginx

## Git Pull

- name: Git pull - Giarrizzo.fr-home
  git:
    repo: git@gitlab.com:bgiarrizzo/giarrizzo.fr.git
    dest: /home/web/giarrizzo.fr/home/
    update: yes
